### ISSUE TITLE
Update for 6.4 - Adoption?

### ISSUE THREAD

**Issue by Stary2001** [PunishedPineapple/Distance#16] opened 2023-05-24 22:07 UTC
The UIMouseover sig was was broken by 6.4 - I've updated it locally, new signature is `E8 ?? ?? ?? ?? 48 8B 5C 24 ?? 4C 8B 74 24 ?? 83 FD` .
I saw one of your other plugins got adopted - would that be the best way to get this released? I'm happy to maintain the plugin bits I think, not sure about the data.

**Comment by PunishedPineapple** [comment] 2023-05-24 23:32
It looks like [Redirect updated](https://github.com/cairthenn/Redirect/compare/e5510fc369d6b719c5bc21b877bc4fa2705215f2..e907a0653db62cdf41035d1fe6398f05b5ab95e6#diff-579d569ccff52d6c0d107ca1aed3291352707d842942d53d2d7ab82b7143b955R28) to use `E8 ?? ?? ?? ?? 48 8B 5C 24 40 4C 8B 74 24 58 83 FD 02`.  I'm not sure whether it's safer to wildcard the operands like in yours or not, but I'm going to just maintain parity with Redirect, since that's where I got this from.  I prefer to err on the side of breaking and requiring an update vs. unintended behavior as well, but I also suck, so idk what's best.  I hope you don't take that as a slight against you in any way.  Thank you for opening the issue.  I will test this sometime tonight and update if everything else still works right too.

As far as adoption goes, if you think you really want to brave the garbage I created and maintain it, I guess ask the people in charge at Goat Place.  I'm fine with whatever they think should be done.  If it's just stuff like updating sigs that are already out there in the wild, I will keep doing that, but if the game has bigger changes, I no longer trust myself to do the work to keep anything going.

**Comment by PunishedPineapple** [comment] 2023-05-24 23:52
Actually, I just got on and Dalamud isn't public yet, so I can't test since it's presumably a staging branch that's up, and I don't have access to that anymore.  Can you confirm that everything else in the plugin works fine with your sig?  If it does, I'll PR the change, since it's so small and already accepted in another plugin.

**Comment by Stary2001** [comment] 2023-05-25 00:06
Yes, I tested it and it seems to work properly as far as I can tell. About the signature, I just took whatever the sigscanner script for ghidra gave me for the func, it probably _is_ better to not have the second wildcards there.

I'll ask them re: adoption - thanks!

**Comment by PunishedPineapple** [comment] 2023-10-19 23:02
Closing this based on the current status of things.

**Closed by PunishedPineapple** 2023-10-19 23:02 UTC
